using System.Collections.Generic;

public static class AuditVariablesAutoGenerated941C
{
    public static Dictionary<string, AuditVariable> Coverage = new Dictionary<string, AuditVariable>();
    public static int ExecutionCounter;
}

public struct AuditVariable
{
    public int Span;
    public int ExecutionCounter;
    public string DocumentPath;
    public string NodePath;
}
